-- Publicidad: contactos legacy (ventas anteriores) + campañas con envío escalonado.
CREATE TABLE IF NOT EXISTS marketing_contacts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL,
  first_name VARCHAR(120) NOT NULL DEFAULT '',
  last_name_p VARCHAR(120) NOT NULL DEFAULT '',
  last_name_m VARCHAR(120) NOT NULL DEFAULT '',
  full_name VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(40) NULL,
  product_name VARCHAR(190) NULL,
  product_code VARCHAR(80) NULL,
  product_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NULL,
  purchased_at DATE NULL,
  notes VARCHAR(500) NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'legacy_import',
  opted_out_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_marketing_contacts_email (email),
  KEY idx_mkt_contacts_product (product_id),
  KEY idx_mkt_contacts_supplier (supplier_id),
  CONSTRAINT fk_mkt_contacts_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_mkt_contacts_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaigns (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  mail_template_code VARCHAR(80) NOT NULL,
  promo_code VARCHAR(40) NULL,
  audience_json JSON NOT NULL,
  status ENUM('draft','scheduled','running','paused','completed','cancelled') NOT NULL DEFAULT 'draft',
  window_start DATE NOT NULL,
  window_end DATE NOT NULL,
  interval_seconds INT UNSIGNED NOT NULL DEFAULT 120,
  day_hour_start TINYINT UNSIGNED NOT NULL DEFAULT 9,
  day_hour_end TINYINT UNSIGNED NOT NULL DEFAULT 18,
  max_per_run INT UNSIGNED NOT NULL DEFAULT 15,
  created_by BIGINT UNSIGNED NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_mkt_campaigns_status (status),
  CONSTRAINT fk_mkt_campaigns_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campaign_recipients (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  campaign_id BIGINT UNSIGNED NOT NULL,
  email VARCHAR(190) NOT NULL,
  full_name VARCHAR(255) NOT NULL DEFAULT '',
  first_name VARCHAR(120) NOT NULL DEFAULT '',
  phone VARCHAR(40) NULL,
  product_label VARCHAR(190) NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'student',
  source_ref VARCHAR(80) NULL,
  scheduled_at DATETIME NOT NULL,
  status ENUM('pending','sent','failed','skipped','cancelled') NOT NULL DEFAULT 'pending',
  sent_at DATETIME NULL,
  last_error VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_mkt_recip_campaign_email (campaign_id, email),
  KEY idx_mkt_recip_due (status, scheduled_at),
  KEY idx_mkt_recip_campaign (campaign_id, status),
  CONSTRAINT fk_mkt_recip_campaign FOREIGN KEY (campaign_id) REFERENCES marketing_campaigns(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
